name: Update prices

on:
  schedule:
    - cron: "12 */2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Update prices
      run: python3 update.py > prices.json

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Commit and push if changed
      run: |
        git add -A .
        DATETIME=$(date +'%Y-%m-%d-%H%M%S')
        git commit -m "update $DATETIME" || exit 0
        git push
