name: Update prices

on:
  schedule:
    - cron: "0 * * * *" # Hourly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-bs4
    
    - name: Update prices
      run: python3 update.py > prices.json

    - name: git push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add -A .
        DATETIME=$(date +'%Y-%m-%d-%H%M%S')
        git commit -m "update $DATETIME" || exit 0
        git push
